### ISSUE TITLE
Battery:SmartBatteryControl:Enable writable?

### ISSUE THREAD

**Issue by slowflyer** [kilianknoll/kostal-RESTAPI#1]
Can the API write the value for attery:SmartBatteryControl:Enable?

I tried, but failed.

Thanks,
slowflyer

**Comment by binderth** [comment]
Syntax should be `kostal-RESTAPI.py -SmartBatteryControl 1` for ON or `kostal-RESTAPI.py -SmartBatteryControl 0` for OFF.

works with me (Kostal Plenticore 10)

**Comment by kilianknoll** [comment]
Also made it more "transparent" how to use the Battery Charging function - hence closing this for now.
